language: android
jdk: oraclejdk9
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26
  - android-26
  - extra-android-m2repository
  - extra-google-m2repository
before_install:
- chmod +x gradlew
- chmod +rx app 
skip_cleanup: true
script: 
  - "sh script/build.sh"
