language: android
jdk: oraclejdk9
android:
  components:
#  - platform-tools
#  - tools-26
  - build-tools-26.1.0
  - android-26
  - extra-android-m2repository
  - extra-google-m2repository
before_install:
- chmod +x gradlew
- chmod +rx app 
skip_cleanup: true
script: 
  - "sh script/build.sh"
